# Generated by Django 4.2.5 on 2024-01-24 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='FaqModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='RateUSModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=250, null=True)),
                ('nick', models.TextField(blank=True, max_length=250, null=True)),
                ('rating', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='RentCarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('idNumber', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('fromDate', models.DateField(default='2023-01-01', max_length=50)),
                ('toDaate', models.DateField(default='2023-01-01', max_length=50)),
                ('otheText', models.TextField(blank=True, max_length=250, null=True)),
                ('carBrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carRental.carmodel')),
            ],
        ),
    ]
