# Generated by Django 4.2.5 on 2024-01-24 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateusmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 18, 0, 23, 442145)),
        ),
        migrations.AlterField(
            model_name='rateusmodel',
            name='nick',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
